#!/bin/bash
#=========================================================================
# Function: Install docker to armbian
# Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian

# Command: armbian-docker
#=========================================================================

# Set font color
blue_font_prefix="\033[94m"
purple_font_prefix="\033[95m"
green_font_prefix="\033[92m"
yellow_font_prefix="\033[93m"
red_font_prefix="\033[91m"
font_color_suffix="\033[0m"
INFO="[${blue_font_prefix}INFO${font_color_suffix}]"
STEPS="[${purple_font_prefix}STEPS${font_color_suffix}]"
SUCCESS="[${green_font_prefix}SUCCESS${font_color_suffix}]"
OPT="[${yellow_font_prefix}OPT${font_color_suffix}]"
ERROR="[${red_font_prefix}ERROR${font_color_suffix}]"

echo -e "${INFO} Welcome to docker installation tool."
echo -e "${INFO} docker安装工具."

echo -e "${STEPS} Initialize the docker installation environment ... "
echo -e "${STEPS} 初始化安装环境 ... "
sudo apt-get update
sudo apt-get remove -y linux-image-current-meson64
sudo apt-get remove -y docker docker-engine docker.io containerd runc
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

# Install GPG certificate
#curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/debian/gpg | apt-key add -
sudo curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | apt-key add -

# Add software source information
#sudo add-apt-repository "deb [arch=arm64,armhf] https://mirrors.aliyun.com/docker-ce/linux/debian $(lsb_release -cs) stable"
sudo add-apt-repository "deb [arch=arm64,armhf] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"

echo -e "${STEPS} Install docker related packages ... "
echo -e "${STEPS} 安装 docker 和 docker-compose ... "
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# Install Docker-compose
wget -O /usr/local/bin/docker-compose https://ghproxy.com/https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-aarch64
chmod +x /usr/local/bin/docker-compose

echo -e "${STEPS} Install docker accelerator ... "
echo -e "${STEPS} 配置国内镜像源 ... "
sudo cat >/etc/docker/daemon.json <<EOF
{
  "bip": "172.31.0.1/24",
  "data-root": "/var/lib/docker/",
  "log-level": "warn",
  "log-driver": "json-file",
  "log-opts": {
     "max-size": "10m",
     "max-file": "5"
   },
  "registry-mirrors": [
     "https://docker.mirrors.ustc.edu.cn",
     "https://registry.cn-shanghai.aliyuncs.com",
     "https://hub-mirror.c.163.com"
   ]
}
EOF
sync
sudo systemctl daemon-reload
sudo systemctl restart docker

# Set up ordinary users to run docker directly
sudo usermod -a -G docker $USER 2>/dev/null

echo -e "${SUCCESS} Docker installed successfully."
echo -e "${SUCCESS} 安装结束."

# Check Version
docker -v
docker-compose -v

exit 0
